# Site settings
author: Hana Leander
title: CODE LEARNER
header-img: img/home-bg.png
email: hana0070@gmail.com
copyright_name: Hana Leander
description: > # this means to ignore newlines until "baseurl:"
  Want to learn code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hana0070

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
